import { usePage } from "@inertiajs/react";

const translations = {
    pt: {
        empresa: "Empresa",
        produtos: "Produtos",
        segmentos: "Segmentos",
        news: "News",
        contato: "Contato",
        trabalheConosco: "Trabalhe Conosco",
        soliciteOrcamento: "Solicite um orçamento",
        pesquisa: "Pesquisa",
        cases: "Cases",
        verTodosOsCases: "Ver todos os cases",
        nossos: "Nossos",
        clientes: "clientes",
        queroSerCliente: "Quero ser cliente",
        aAguiaInox: "A Águia Inox",
        conhecaAguaInox: "Conheça a Águia Inox",
        verTodasNoticias: "Ver todas as notícias",
        aceito: "Aceito a ",
        termosUso: "Termos de uso",
        ea: " e a ",
        politicaPrivacidade: "Política de privacidade",
        siteAguiaInox: " do site da Águia Inox",
        enviarMensagem: "Enviar mensagem",
        enviandoMensagem: "Enviando...",
        newsletterTexto: "Cadastre-se para receber novidades e informações.",
        seuNome: "Seu nome",
        nomeDaEmpresa: "Nome da empresa",
        seuCargo: "Seu cargo",
        seuEmail: "Seu E-mail",
        selecioneOSetor: "Selecione o setor",
        assunto: "Assunto",
        escreverMensagem: "Escrever mensagem...",
        cadastrando: "Cadastrando...",
        cadastrar: "Cadastrar",
        historia: "História",
        selos: "Selos",
        missaoVisaoValores: "Missão, visão e valores",
        diferenciais: "Diferenciais",
        voltarAoTopo: "Voltar ao topo",
        nossasRedes: "Nossas redes",
        desenvolvidoPor: "Desenvolvido por",
        selo: "Selo",
        solicitarOrcamento: "Solicitar orçamento",
        sobreEsseSegmento: "Sobre esse segmento",
        conhecerProduto: "Conhecer Produto",
        sejaParceiro: "Seja um parceiro",
        sejaParceiroTexto:
            "Temos certeza que podemos oferecer a melhor solução para o seu projeto. Converse com a nossa equipe técnica e invista para melhorar os seus processos e levar a sua empresa para um novo patamar de qualidade, entrega e resultados.",
        continuarLendo: "Continuar lendo",
        destaques: "Destaques",
        todos: "Todos",
        exploreNossosCases: "Explore nossos cases",
        verProjetoCompleto: "Ver o projeto completo",
        preenchaCurriculo: "Preencha seu currículo aqui",
        depoimentosColaboradores: "Depoimentos de nossos colaboradores",
        seuCNPJ: "Seu CNPJ",
        seuTelefone: "Seu telefone: (DDD) + Número",
        selecioneOAssunto: "Selecione o assunto",
        comercial: "Comercial",
        parceria: "Parceria",
        investimento: "Investimento",
        outros: "Outros",
        newsSucesso: "E-mail cadastrado com sucesso!",
        parceriaSucesso: "Mensagem enviada com sucesso!",
        resultadosPesquisa: "Resultados da pesquisa para",
        opcionais: "Opcionais",
        downloads: "Downloads",
        galeriaProjeto: "Galeria de imagens do projeto",
        vejaTambem: "Veja também",
        cookies:
            "Utilizamos cookies para oferecer uma melhor experiência, melhorar o desempenho, analisar como você interage em nosso site e personalizar conteúdo. Para mais informações acesse nossa",
        cookiePolitica: "política de privacidade",
        cookieAceitar: "Aceitar todos os cookies",
        filtrosNaoEncontrados:
            "Não foram encontradas postagens com o filtro selecionado",
        categoriaNaoEncontrada: "Nenhuma categoria disponível",
        compartilhe: 'Compartilhe esse conteúdo em suas redes sociais',
        voltarProdutos: "Voltar a página de produtos",
        recolher: 'Recolher',
        expandir: 'Ver Mais Categorias +'
    },
    en: {
        empresa: "Company",
        produtos: "Products",
        segmentos: "Segments",
        news: "News",
        contato: "Contact",
        trabalheConosco: "Work with us",
        soliciteOrcamento: "Request a quote",
        sobreEsseSegmento: "About this segment",
        pesquisa: "Search",
        cases: "Cases",
        verTodosOsCases: "View all cases",
        nossos: "Our",
        clientes: "clients",
        queroSerCliente: "I want to be a client",
        aAguiaInox: "Águia Inox",
        conhecaAguaInox: "Meet Águia Inox",
        verTodasNoticias: "View all news",
        aceito: "I accept the ",
        termosUso: "Terms of Use",
        ea: " and the ",
        politicaPrivacidade: "Privacy Policy",
        siteAguiaInox: " from the Águia Inox website",
        enviarMensagem: "Send message",
        enviandoMensagem: "Sending...",
        newsletterTexto: "Sign up to receive news and information.",
        seuNome: "Your name",
        nomeDaEmpresa: "Company name",
        seuCargo: "Your position",
        seuEmail: "Your email",
        selecioneOSetor: "Select the department",
        assunto: "Subject",
        escreverMensagem: "Write your message...",
        cadastrando: "Registering...",
        cadastrar: "Register",
        historia: "History",
        selos: "Seals",
        missaoVisaoValores: "Mission, vision and values",
        diferenciais: "Differentials",
        voltarAoTopo: "Back to top",
        nossasRedes: "Our social media",
        desenvolvidoPor: "Developed by",
        selo: "Seal",
        solicitarOrcamento: "Request a quote",
        sobreEsseSegmento: "About this segment",
        conhecerProduto: "Learn about the product",
        sejaParceiro: "Be a partner",
        sejaParceiroTexto:
            "We are sure we can offer the best solution for your project. Talk to our technical team and invest to improve your processes and take your company to a new level of quality, delivery, and results.",
        continuarLendo: "Continue reading",
        destaques: "Highlights",
        todos: "All",
        exploreNossosCases: "Explore our cases",
        verProjetoCompleto: "View the full project",
        preenchaCurriculo: "Fill out your resume here",
        depoimentosColaboradores: "Testimonials from our collaborators",
        seuCNPJ: "Your CNPJ",
        seuTelefone: "Your phone: (Area code) + Number",
        selecioneOAssunto: "Select the subject",
        comercial: "Commercial",
        parceria: "Partnership",
        investimento: "Investment",
        outros: "Others",
        newsSucesso: "Email successfully registered!",
        parceriaSucesso: "Message sent successfully!",
        resultadosPesquisa: "Search results for",
        opcionais: "Optionals",
        downloads: "Downloads",
        galeriaProjeto: "Project image gallery",
        vejaTambem: "See also",
        cookies:
            "We use cookies to offer a better experience, improve performance, analyze how you interact with our site, and personalize content. For more information, please visit our",
        cookiePolitica: "privacy policy",
        cookieAceitar: "Accept all cookies",
        filtrosNaoEncontrados: "No posts were found with the selected filter",
        categoriaNaoEncontrada: "No category available",
        compartilhe: 'Share this content on your social media',
        voltarProdutos: "Back to products page",
        recolher: 'Minimize',
        expandir: 'See More Categories +'

    },
    es: {
        empresa: "Empresa",
        produtos: "Productos",
        segmentos: "Segmentos",
        news: "Noticias",
        contato: "Contacto",
        trabalheConosco: "Trabaje con Nosotros",
        soliciteOrcamento: "Solicite un Presupuesto",
        sobreEsseSegmento: "Sobre este segmento",
        pesquisa: "Buscar",
        cases: "Casos",
        verTodosOsCases: "Ver todos los casos",
        nossos: "Nuestros",
        clientes: "clientes",
        queroSerCliente: "Quiero ser cliente",
        aAguiaInox: "Águia Inox",
        conhecaAguaInox: "Conozca Águia Inox",
        verTodasNoticias: "Ver todas las noticias",
        aceito: "Acepto los ",
        termosUso: "Términos de uso",
        ea: " y la ",
        politicaPrivacidade: "Política de privacidad",
        siteAguiaInox: " del sitio web de Águia Inox",
        enviarMensagem: "Enviar mensaje",
        enviandoMensagem: "Enviando...",
        newsletterTexto: "Regístrese para recibir novedades e información.",
        seuNome: "Su nombre",
        nomeDaEmpresa: "Nombre de la empresa",
        seuCargo: "Su cargo",
        seuEmail: "Su correo electrónico",
        selecioneOSetor: "Seleccione el sector",
        assunto: "Asunto",
        escreverMensagem: "Escriba su mensaje...",
        cadastrando: "Registrando...",
        cadastrar: "Registrarse",
        historia: "Historia",
        selos: "Sellos",
        missaoVisaoValores: "Misión, visión y valores",
        diferenciais: "Diferenciales",
        voltarAoTopo: "Volver al inicio",
        nossasRedes: "Nuestras redes",
        desenvolvidoPor: "Desarrollado por",
        selo: "Sello",
        solicitarOrcamento: "Solicitar presupuesto",
        sobreEsseSegmento: "Acerca de este segmento",
        conhecerProduto: "Conocer el producto",
        sejaParceiro: "Sea un socio",
        sejaParceiroTexto:
            "Estamos seguros de que podemos ofrecer la mejor solución para su proyecto. Hable con nuestro equipo técnico e invierta para mejorar sus procesos y llevar su empresa a un nuevo nivel de calidad, entrega y resultados.",
        continuarLendo: "Seguir leyendo",
        destaques: "Destacados",
        todos: "Todos",
        exploreNossosCases: "Explore nuestros casos",
        verProjetoCompleto: "Ver el proyecto completo",
        preenchaCurriculo: "Complete su currículum aquí",
        depoimentosColaboradores: "Testimonios de nuestros colaboradores",
        seuCNPJ: "Su CNPJ",
        seuTelefone: "Su teléfono: (Código de área) + Número",
        selecioneOAssunto: "Seleccione el asunto",
        comercial: "Comercial",
        parceria: "Alianza",
        investimento: "Inversión",
        outros: "Otros",
        newsSucesso: "¡Correo registrado con éxito!",
        parceriaSucesso: "¡Mensaje enviado con éxito!",
        resultadosPesquisa: "Resultados de la búsqueda para",
        opcionais: "Opcionales",
        downloads: "Descargas",
        galeriaProjeto: "Galería de imágenes del proyecto",
        vejaTambem: "Ver también",
        cookies:
            "Utilizamos cookies para ofrecer una mejor experiencia, mejorar el rendimiento, analizar cómo interactúa con nuestro sitio y personalizar el contenido. Para obtener más información, visite nuestra",
        cookiePolitica: "política de privacidad",
        cookieAceitar: "Aceptar todas las cookies",
        filtrosNaoEncontrados:
            "No se encontraron publicaciones con el filtro seleccionado",
        categoriaNaoEncontrada: "Ninguna categoría disponible",
        compartilhe: 'Comparte este contenido en tus redes sociales',
        voltarProdutos: "Volver a la página de productos",
        recolher: 'Recoger',
        expandir: 'Ver más categorías +'

    },
};

export function useLang() {
    const { idioma } = usePage().props;

    return (key) => translations[idioma]?.[key] || key;
}
